class_weights:
  ggh: 258.5812902826239
  misc: 365.9549142283764
  qqh: 1617.190468530144
  ss: 5.225792063605562
  tt: 15.98752139177283
  w: 5.653636444999225
  zll: 7.239897344500587
  ztt: 2.3591935261960053
classes:
- ggh
- qqh
- ztt
- zll
- w
- tt
- ss
- misc
datasets:
- ml/2016_et/fold0_training_dataset.root
- ml/2016_et/fold1_training_dataset.root
event_weights: training_weight
global_weight_scale: 1.0
model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  name: smhtt_dropout_tanh
  save_best_only: true
output_path: ml/2016_et
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75
variables:
- pt_2
- jpt_1
- jpt_2
- bpt_1
- bpt_2
- njets
- nbtag
- m_sv
- mt_1
- mt_2
- ptvis
- pt_tt
- mjj
- jdeta
- m_vis
- dijetpt
- met
