class_weights:
#  ggh: 223318.85667015924
  misc: 256.8364327109257
  qqh: 1836.246024244309
  ss: 6.616897459060372
  tt: 18.00263337566449
  w: 6.799547536309369
  zll: 13.66888192361698
  ztt: 1.7585377716013677
classes:
#- ggh
- qqh
- ztt
- zll
- w
- tt
- ss
- misc
datasets:
- ml/2016_mt/fold0_training_dataset.root
- ml/2016_mt/fold1_training_dataset.root
event_weights: training_weight
global_weight_scale: 1.0
model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  name: smhtt_dropout_tanh
  save_best_only: true
output_path: ml/2016_mt
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75
variables:
- pt_1
- pt_2
- jpt_1
- jpt_2
- bpt_1
- bpt_2
- njets
- nbtag
- m_fastmtt
- mt_1
- mt_2
- ptvis
- pt_tt
- mjj
- jdeta
- m_vis
- dijetpt
- met
