class_weights:
  ggh: 209.0
  misc: 233.94783528447502
  qqh: 1625.8154894249649
  ss: 5.2536629709709475
  tt: 16.072788222578335
  w: 5.683789190404755
  zll: 7.004423533084532
  ztt: 2.3593573453276306
classes:
#- ggh
- qqh
- ztt
- zll
- w
- tt
- ss
- misc
datasets:
- ml/2016_et/fold0_training_dataset.root
- ml/2016_et/fold1_training_dataset.root
event_weights: training_weight
global_weight_scale: 1.0
model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  name: smhtt_dropout_tanh
  save_best_only: true
output_path: ml/2016_et
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75
variables:
- pt_2
- jpt_1
- jpt_2
- bpt_1
- bpt_2
- njets
- nbtag
- m_sv
- mt_1
- mt_2
- ptvis
- pt_tt
- mjj
- jdeta
- m_vis
- dijetpt
- met
