class_weights:
  ggh: 241.36803191752904
  misc: 10.526449079155576
  noniso: 1.52653125620745
  qqh: 590.1229311109338
  ztt: 4.096956063741624
classes:
- ggh
- qqh
- ztt
- noniso
- misc
datasets:
- ml/2016_tt/fold0_training_dataset.root
- ml/2016_tt/fold1_training_dataset.root
event_weights: training_weight
global_weight_scale: 1.0
model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  name: smhtt_dropout_tanh
  save_best_only: true
output_path: ml/2016_tt
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75
variables:
- pt_1
- pt_2
- jpt_1
- jpt_2
- bpt_1
- bpt_2
- nbtag
- m_sv
- mt_1
- mt_2
- ptvis
- pt_tt
- mjj
- jdeta
- m_vis
- dijetpt
- met
