class_weights:
  ggh: 191.4583769068112
  misc: 55.538791940478944
  qqh: 1549.1761839898736
  ss: 5.582443648692467
  tt: 15.188188568663193
  w: 5.736539094478119
  zll: 16.768407504004394
  ztt: 2.0112822968604043
classes:
- ggh
- qqh
- ztt
- zll
- w
- tt
- ss
- misc
datasets:
- ml/2016_mt/fold0_training_dataset.root
- ml/2016_mt/fold1_training_dataset.root
event_weights: training_weight
global_weight_scale: 1.0
model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  name: smhtt_dropout_tanh
  save_best_only: true
output_path: ml/2016_mt
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75
variables:
- pt_1
- pt_2
- jpt_1
- jpt_2
- bpt_1
- bpt_2
- njets
- nbtag
- mt_1
- mt_2
- ptvis
- pt_tt
- mjj
- jdeta
- m_vis
- dijetpt
- met
