# Training datasets for different folds
datasets:
    - ml/2017_mt/fold0_training_dataset.root
    - ml/2017_mt/fold1_training_dataset.root

# Base path for all output files
output_path: ml/2017_mt

# Define classes based on tree names in dataset file
classes:
    - ggh
    - qqh
    - ztt
    - zll
    - w
    - tt
    - ss
    - misc

# Set class weights
class_weights:
    ggh: 274.4
    qqh: 3004.0
    ztt: 1.9
    zll: 19.7
    w: 5.9
    tt: 17.2
    ss: 5.4
    misc: 75.5

# Define global scale factor, which is multiplied to all event weights
global_weight_scale: 1.0

# Set event weight variable
event_weights: training_weight

# Define list of variables to be used for training
variables:
    - pt_1
    - pt_2
    # iso_1     # Failed 1D GoF
    # iso_2     # Failed 1D GoF
    - jpt_1
    - jpt_2
    - bpt_1
    - bpt_2
    - njets
    - nbtag
    - m_sv
    - mt_1
    # mt_2      # Failed 1D GoF
    # ptvis     # Failed 1D GoF
    - pt_tt
    - mjj
    - jdeta
    # m_vis     # Failed 1D GoF
    - dijetpt
    # met       # Failed 1D GoF

# Split of dataset in training and validation (in TMVA called training and testing)
train_test_split: 0.75

# Define preprocessing
preprocessing: standard_scaler

# Set random seed for initialization of parameters and dataset splits
seed: 1234

# Define the model parameter
model:
    name: smhtt_dropout_tanh
    batch_size: 100
    epochs: 100000
    early_stopping: 50
    save_best_only: true
