# Training datasets for different folds
datasets:
    - ml/2017_em/fold0_training_dataset.root
    - ml/2017_em/fold1_training_dataset.root

# Base path for all output files
output_path: ml/2017_em

# Define classes based on tree names in dataset file
classes:
    - ggh
    - qqh
    - ztt
    - tt
    - ss
    - misc
    - db

# Set class weights
class_weights:
    ggh: 826.2
    qqh: 6711.6
    ztt: 4.0
    tt: 2.0
    ss: 8.3
    misc: 24.9
    db: 12.2

# Define global scale factor, which is multiplied to all event weights
global_weight_scale: 1.0

# Set event weight variable
event_weights: training_weight

# Define list of variables to be used for training
variables:
    - pt_1
    - pt_2
    - eta_1
    - eta_2
    - m_vis
    - ptvis
    - pt_tt
    - pt_ttjj
    - m_sv
    - eta_sv
    - ME_D
    - ME_costheta1
    - ME_costheta2
    - ME_costhetastar
    - ME_phi
    - ME_phi1
    - ME_q2v1
    - ME_q2v2
    - bpt_1
    - bpt_2
    - nbtag
    - jpt_1
    - jpt_2
    - njets
    - jdeta
    - mjj
    - dijetpt
    - met
    - pZetaMissVis
    - mTdileptonMET

# Split of dataset in training and validation (in TMVA called training and testing)
train_test_split: 0.75

# Define preprocessing
preprocessing: standard_scaler

# Set random seed for initialization of parameters and dataset splits
seed: 1234

# Define the model parameter
model:
    name: smhtt_dropout_tanh
    batch_size: 100
    epochs: 100000
    early_stopping: 50
    save_best_only: true
