class_weights:
  db: 17.253056535891872
  ggh: 346.5932531182222
  misc: 21.589786879317202
  qqh: 2977.8359856616285
  ss: 5.688666329188941
  tt: 15.763093580334802
  ztt: 1.5307546202198048

datasets:
  - ml/2017_em/fold0_training_dataset.root
  - ml/2017_em/fold1_training_dataset.root

event_weights: training_weight
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75

output_path: ml/2017_em_10_variables
output_path_json: ml/2017_em_10_variables

classes:
  - ggh
  - qqh
  - ztt
  - tt
  - ss
  - misc
  - db

variables:
  - pt_1
  - pt_2
  #- jpt_1
  - jpt_2
  #- bpt_1
  #- bpt_2
  - njets
  - nbtag
  - m_sv
  #- mt_1
  #- mt_2
  - ptvis
  #- pt_tt
  - mjj
  #- jdeta
  - m_vis
  - dijetpt
  #- met
#  - dr_tt
#  - jeta_1
#  - jeta_2
#  - pZetaMiss
#  - pZetaVis
#  - mt_max
#  - dzeta
#  - pt_sv
#  - pt_ttjj

global_weight_scale: 1.0

model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  name: smhtt_dropout_relu
  save_best_only: true

