class_weights:
  ggh: 194.4478588110794
  misc: 12.820116495768385
  noniso: 1.4373483972743835
  qqh: 600.2050650645273
  ztt: 4.556573048498282

classes:
  - ggh
  - qqh
  - ztt
  - noniso
  - misc

datasets:
  - ml/2017_tt/fold0_training_dataset.root
  - ml/2017_tt/fold1_training_dataset.root


output_path: ml/2017_tt_10_variables
output_path_json: ml/2017_27_10_variables

variables:
  - pt_1
  - pt_2
  #- jpt_1
  - jpt_2
  #- bpt_1
  #- bpt_2
  - njets
  - nbtag
  - m_sv
  #- mt_1
  #- mt_2
  - ptvis
  #- pt_tt
  - mjj
  #- jdeta
  - m_vis
  - dijetpt
  #- met

event_weights: training_weight
global_weight_scale: 1.0
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75

model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  learning_rate: 1e-3
  name: smhtt_dropout_relu
  save_best_only: true