# Training datasets for different folds
datasets:
    - ml/2017_et/fold0_training_dataset.root
    - ml/2017_et/fold1_training_dataset.root

# Base path for all output files
output_path: ml/2017_et_pruned
output_path_json: ml/2017_et_pruned

# Define classes based on tree names in dataset file
classes:
    - ggh
    - qqh
    - ztt
    - zll
    - w
    - tt
    - ss
    - misc

# Set class weights
class_weights:
    ggh: 218.5
    qqh: 1598.8
    ztt: 2.7
    zll: 5.6
    w: 5.5
    tt: 13.0
    ss: 5.9
    misc: 63.1

# Define global scale factor, which is multiplied to all event weights
global_weight_scale: 1.0

# Set event weight variable
event_weights: training_weight

# Define list of variables to be used for training
variables:
    #- pt_1      # Failed 1D GoF
    - pt_2
    #- iso_1     # Failed 1D GoF
    #- iso_2     # Failed 1D GoF
    - jpt_1
    #- jpt_2
    #- bpt_1
    #- bpt_2
    #- njets
    - nbtag
    #- m_sv
    #- mt_1
    #- mt_2
    - ptvis
    #- pt_tt
    #- mjj
    #- jdeta
    - m_vis     # Failed 2D GoF
    - dijetpt
    #- met
    #- ME_D

# Split of dataset in training and validation (in TMVA called training and testing)
train_test_split: 0.75

# Define preprocessing
preprocessing: standard_scaler

# Set random seed for initialization of parameters and dataset splits
seed: 1234

# Define the model parameter
model:
    name: smhtt_dropout_relu
    batch_size: 100
    epochs: 100000
    early_stopping: 50
    learning_rate: 1e-3
    save_best_only: true
