class_weights:
  ggh: 219.5462147320035
  misc: 51.73810202168948
  qqh: 1602.7933186342161
  ss: 5.909552126436286
  tt: 12.999519836254832
  w: 5.495012619736802
  zll: 5.599740849073923
  ztt: 2.711594178210849

classes:
  - ggh
  - qqh
  - ztt
  - zll
  - w
  - tt
  - ss
  - misc

datasets:
  - ml/2017_et/fold0_training_dataset.root
  - ml/2017_et/fold1_training_dataset.root

output_path: ml/2017_et_10_variables
output_path_json: ml/2017_et_10_variables

variables:
  - pt_1
  - pt_2
  #- jpt_1
  - jpt_2
  #- bpt_1
  #- bpt_2
  - njets
  - nbtag
  - m_sv
  #- mt_1
  #- mt_2
  - ptvis
  #- pt_tt
  - mjj
  #- jdeta
  - m_vis
  - dijetpt
  #- met

event_weights: training_weight
global_weight_scale: 1.0
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75

model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  learning_rate: 1e-3
  name: smhtt_dropout_relu
  save_best_only: true