# Training datasets for different folds
datasets:
    - ml/2017_mt/fold0_training_dataset.root
    - ml/2017_mt/fold1_training_dataset.root

# Base path for all output files
output_path: ml/2017_mt

# Define classes based on tree names in dataset file
classes:
    - ggh
    - qqh
    - ztt
    - zll
    - w
    - tt
    - ss
    - misc

# Set class weights
class_weights:
    ggh: 137.6
    qqh: 2864.7
    ztt: 1.9
    zll: 19.8
    w: 5.9
    tt: 17.3
    ss: 5.4
    misc: 75.9

# Define global scale factor, which is multiplied to all event weights
global_weight_scale: 1.0

# Set event weight variable
event_weights: training_weight

# Define list of variables to be used for training
# NOTE: This is the selection based on 2016 data.
variables:
    - pt_1
    - pt_2
#   - phi_2
    - jpt_1
    - jpt_2
#   - jeta_1
#   - jeta_2
#   - jphi_1
#   - jphi_2
    - jm_1
    - jm_2
#   - jmva_2
    - bpt_1
    - bpt_2
#   - beta_1
#   - beta_2
#   - bphi_1
#   - bphi_2
    - bcsv_1
#   - bcsv_2
    - njets
#   - nbtag
    - m_sv
    - ptvis
    - pt_tt
    - mjj
    - m_vis
#   - dijetphi
    - dijetpt
    - met

# Split of dataset in training and validation (in TMVA called training and testing)
train_test_split: 0.75

# Define preprocessing
preprocessing: standard_scaler

# Set random seed for initialization of parameters and dataset splits
seed: 1234

# Define the model parameter
model:
    name: smhtt_dropout_tanh
    batch_size: 100
    epochs: 100000
    early_stopping: 50
    save_best_only: true
