class_weights:
  ggh: 11.984715408463664
  misc: 15.540579086897484
  noniso: 1.5939914231178718
  qqh: 35.323705624552424
  ztt: 5.087837096711277
classes:
- ggh
- qqh
- ztt
- noniso
- misc
datasets:
- ml/2018_tt/fold0_training_dataset.root
- ml/2018_tt/fold1_training_dataset.root
event_weights: training_weight
global_weight_scale: 1.0
model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  name: smhtt_dropout_tanh
  save_best_only: true
output_path: ml/2018_tt
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75
variables:
- pt_1
- pt_2
- eta_1
- eta_2
- m_vis
- ptvis
- pt_tt
- pt_ttjj
- m_sv
- eta_sv
- ME_costheta1
- ME_costheta2
- ME_costhetastar
- ME_phi
- ME_phi1
- ME_q2v1
- ME_q2v2
- bpt_1
- bpt_2
- nbtag
- jpt_1
- jpt_2
- njets
- jdeta
- mjj
- dijetpt
- met
- pZetaMissVis
- mTdileptonMET
