class_weights:
  ggh: 10.914828791935367
  misc: 51.924787042130845
  qqh: 68.99883866249614
  ss: 6.348063581153123
  tt: 12.902991462078063
  w: 5.393309034885091
  zll: 8.669113728039385
  ztt: 2.951304941208795
classes:
- ggh
- qqh
- ztt
- zll
- w
- tt
- ss
- misc
datasets:
- ml/2018_et/fold0_training_dataset.root
- ml/2018_et/fold1_training_dataset.root
event_weights: training_weight
global_weight_scale: 1.0
model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  name: smhtt_dropout_tanh
  save_best_only: true
output_path: ml/2018_et
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75
variables:
- pt_1
- pt_2
- eta_1
- eta_2
- m_vis
- ptvis
- pt_tt
- pt_ttjj
- m_sv
- eta_sv
- ME_costheta1
- ME_costheta2
- ME_costhetastar
- ME_phi
- ME_phi1
- ME_q2v1
- ME_q2v2
- bpt_1
- bpt_2
- nbtag
- jpt_1
- jpt_2
- njets
- jdeta
- mjj
- dijetpt
- met
- pZetaMissVis
- mTdileptonMET
