class_weights:
  db: 7.730150285401895
  ggh: 24.47426220324668
  misc: 15.404475569718114
  qqh: 150.98905863530717
  ss: 5.831217336268383
  tt: 6.4132652830638825
  ztt: 2.3211529877981207
classes:
- ggh
- qqh
- ztt
- tt
- ss
- misc
- db
datasets:
- ml/2018_em/fold0_training_dataset.root
- ml/2018_em/fold1_training_dataset.root
event_weights: training_weight
global_weight_scale: 1.0
model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  name: smhtt_dropout_tanh
  save_best_only: true
output_path: ml/2018_em
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75
variables:
- pt_1
- pt_2
- eta_1
- eta_2
- m_vis
- ptvis
- pt_tt
- pt_ttjj
- m_sv
- eta_sv
- ME_costheta1
- ME_costheta2
- ME_costhetastar
- ME_phi
- ME_phi1
- ME_q2v1
- ME_q2v2
- bpt_1
- bpt_2
- nbtag
- jpt_1
- jpt_2
- njets
- jdeta
- mjj
- dijetpt
- met
- pZetaMissVis
- mTdileptonMET
