#!/bin/bash
## for both:
anaSSStep=0

## for  anaSignalStrength-MCvsEMB.sh
mc_ds_created=0
emb_ds_created=0

mc_sum_training_weights=0
emb_sum_training_weights=0

mc_training=0
emb_training=0

mc_testing=0
emb_testing=0

mc_models_exported=0
emb_models_exported=0

mc_NNApplication_started=0
emb_NNApplication_started=0

mc_NNApplication_ended=0
emb_NNApplication_ended=0

mc_NNApplication_collected=0
emb_NNApplication_collected=0

mc_NNApplication_synced=0
emb_NNApplication_synced=0

### for run_complete

ds_created=0
sum_training_weights=0
training=0
models_exported=0
NNApplication_started=0
NNApplication_ended=0
NNApplication_collected=0
NNApplication_synced=0
