#!/bin/bash
## for both:
anaSSStep=2

### for run all
mc_mc_ds_created=0
mc_ff_ds_created=0
emb_mc_ds_created=0
emb_ff_ds_created=0

mc_mc_sum_training_weights=0
mc_ff_sum_training_weights=0
emb_mc_sum_training_weights=0
emb_ff_sum_training_weights=0

mc_mc_training=0
mc_ff_training=0
emb_mc_training=0
emb_ff_training=0

mc_mc_testing=0
mc_ff_testing=0
emb_mc_testing=0
emb_ff_testing=0

mc_mc_models_exported=0
mc_ff_models_exported=0
emb_mc_models_exported=0
emb_ff_models_exported=0

mc_mc_NNApplication_started=0
mc_ff_NNApplication_started=0
emb_mc_NNApplication_started=0
emb_ff_NNApplication_started=0

mc_mc_NNApplication_ended=0
mc_ff_NNApplication_ended=0
emb_mc_NNApplication_ended=0
emb_ff_NNApplication_ended=0

mc_mc_NNApplication_collected=0
mc_ff_NNApplication_collected=0
emb_mc_NNApplication_collected=0
emb_ff_NNApplication_collected=0

mc_mc_NNApplication_synced=0
mc_ff_NNApplication_synced=0
emb_mc_NNApplication_synced=0
emb_ff_NNApplication_synced=0


## for  anaSignalStrength-MCvsEMB.sh
mc_ds_created=1
emb_ds_created=1

mc_sum_training_weights=1
emb_sum_training_weights=1

mc_training=1
emb_training=1

mc_testing=1
emb_testing=1

mc_models_exported=1
emb_models_exported=1

mc_NNApplication_started=1
emb_NNApplication_started=1

mc_NNApplication_ended=1
emb_NNApplication_ended=1

mc_NNApplication_collected=1
emb_NNApplication_collected=1

mc_NNApplication_synced=1
emb_NNApplication_synced=1

### for run_complete

ds_created=0
sum_training_weights=0
training=0
models_exported=0
NNApplication_started=0
NNApplication_ended=0
NNApplication_collected=0
NNApplication_synced=0
