m_vis:
    outputdir: "/storage/c/swozniewski/SM_Htautau/ntuples/Artus_2018-07-06/fake_factor_friends"
    et:
        expression: "m_vis"
        binning: [0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200]
    mt:
        expression: "m_vis"
        binning: [0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200]
    tt:
        expression: "m_vis"
        binning: [0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200]
NN_score:
    outputdir: "/storage/c/wunsch/Artus_2018-08-11/fake_factor_friends_NN_score"
    et:
        expression: "et_max_score"
        binning: [0.2, 0.4, 0.6, 1.0]
    mt:
        expression: "mt_max_score"
        binning: [0.2, 0.4, 0.6, 1.0]
    tt:
        expression: "tt_max_score"
        binning: [0.2, 0.4, 0.6, 1.0]
