class_weights:
  ggh: 212.3346062909674
  misc: 9.900178353165487
  noniso: 1.537756394620113
  qqh: 594.462319220591
  ztt: 4.12708246875239
classes:
- ggh
- qqh
- ztt
- noniso
- misc
datasets:
- ml/2016_tt/fold0_training_dataset.root
- ml/2016_tt/fold1_training_dataset.root
event_weights: training_weight
global_weight_scale: 1.0
model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  name: smhtt_dropout_tanh
  save_best_only: true

preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75
variables:
- pt_1
- pt_2
- m_vis
- ptvis
- m_sv
- nbtag
- jpt_1
- njets
- jdeta
- mjj
- dijetpt
