
# Base path for all output files


# Define classes based on tree names in dataset file
classes:
    - ggh
    - qqh
    - ztt
    - zll
    - w
    - tt
    - ss
    - misc

# Set class weights
class_weights:
    ggh:  297.2
    qqh:  2432.6
    ztt: 2.7
    zll: 18.2
    w: 3.7
    tt: 7.9
    ss: 6.4
    misc:  40.0

# Define global scale factor, which is multiplied to all event weights
global_weight_scale: 1.0

# Set event weight variable
event_weights: training_weight

# Define list of variables to be used for training
variables:
- pt_1
- pt_2
- m_vis
- ptvis
- m_sv_puppi
- nbtag
- jpt_1
- njets
- jdeta
- mjj
- dijetpt

# Split of dataset in training and validation (in TMVA called training and testing)
train_test_split: 0.75

# Define preprocessing
preprocessing: standard_scaler

# Set random seed for initialization of parameters and dataset splits
seed: 1234

# Define the model parameter
model:
    name: smhtt_dropout_tanh
    batch_size: 100
    epochs: 100000
    early_stopping: 50
    save_best_only: true
    steps_per_epoch: 1000
