
# Base path for all output files


# Define classes based on tree names in dataset file
classes:
    - ggh
    - qqh
    - ztt
    - zll
    - w
    - tt
    - ss
    - misc

# Set class weights
class_weights:
    ggh: 347.7
    qqh: 2597.5
    ztt: 4.5
    zll: 7.4
    w: 3.4
    tt: 7.3
    ss: 5.4
    misc: 37.6

# Define global scale factor, which is multiplied to all event weights
global_weight_scale: 1.0

# Set event weight variable
event_weights: training_weight

# Define list of variables to be used for training
variables:
- pt_1
- pt_2
- m_vis
- ptvis
- m_sv_puppi
- nbtag
- jpt_1
- njets
- jdeta
- mjj
- dijetpt

# Split of dataset in training and validation (in TMVA called training and testing)
train_test_split: 0.75

# Define preprocessing
preprocessing: standard_scaler

# Set random seed for initialization of parameters and dataset splits
seed: 1234

# Define the model parameter
model:
    name: smhtt_dropout_tanh
    batch_size: 100
    epochs: 100000
    early_stopping: 50
    save_best_only: true
