class_weights:
  ggh: 11.984715408463664
  misc: 15.540579086897484
  noniso: 1.5939914231178718
  qqh: 35.323705624552424
  ztt: 5.087837096711277
classes:
- ggh
- qqh
- ztt
- noniso
- misc
event_weights: training_weight
global_weight_scale: 1.0
model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  name: smhtt_dropout_tanh
  save_best_only: true
  steps_per_epoch: 1000
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75
variables:
- pt_1
- pt_2
- m_vis
- ptvis
- m_sv
- nbtag
- jpt_1
- njets
- jdeta
- mjj
- dijetpt
