class_weights:
  ggh: 10.914828791935367
  misc: 51.924787042130845
  qqh: 68.99883866249614
  ss: 6.348063581153123
  tt: 12.902991462078063
  w: 5.393309034885091
  zll: 8.669113728039385
  ztt: 2.951304941208795
classes:
- ggh
- qqh
- ztt
- zll
- w
- tt
- ss
- misc
event_weights: training_weight
global_weight_scale: 1.0
model:
  batch_size: 100
  early_stopping: 50
  epochs: 100000
  name: smhtt_dropout_tanh
  save_best_only: true
  steps_per_epoch: 1000
output_path: ml/out/2018_et
preprocessing: standard_scaler
seed: 1234
train_test_split: 0.75
variables:
- pt_1
- pt_2
- m_vis
- ptvis
- m_sv
- nbtag
- jpt_1
- njets
- jdeta
- mjj
- dijetpt
